# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: physarum.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='physarum.proto',
  package='physarium',
  syntax='proto3',
  serialized_options=b'Z\036github.com/theo-m/physarium/pb',
  serialized_pb=b'\n\x0ephysarum.proto\x12\tphysarium\"\xd3\x02\n\x06\x43onfig\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x11\n\tparticles\x18\x03 \x01(\x03\x12\x12\n\niterations\x18\x04 \x01(\x05\x12\x13\n\x0b\x62lur_radius\x18\x05 \x01(\x05\x12\x13\n\x0b\x62lur_passes\x18\x06 \x01(\x05\x12\x13\n\x0bzoom_factor\x18\x07 \x01(\x02\x12&\n\x06\x61gents\x18\t \x03(\x0b\x32\x16.physarium.AgentConfig\x12\x1a\n\x12interaction_matrix\x18\n \x03(\x02\x12\x31\n\x05idist\x18\x0b \x01(\x0e\x32\".physarium.Config.InitDistribution\"M\n\x10InitDistribution\x12\x07\n\x03UNK\x10\x00\x12\x0b\n\x07UNIFORM\x10\x01\x12\r\n\tCENTROIDS\x10\x02\x12\n\n\x06\x43\x45NTRE\x10\x03\x12\x08\n\x04GRID\x10\x04\"\xab\x01\n\x0b\x41gentConfig\x12\x14\n\x0csensor_angle\x18\x01 \x01(\x02\x12\x17\n\x0fsensor_distance\x18\x02 \x01(\x02\x12\x16\n\x0erotation_angle\x18\x03 \x01(\x02\x12\x15\n\rstep_distance\x18\x04 \x01(\x02\x12\x19\n\x11\x64\x65position_amount\x18\x05 \x01(\x02\x12\x14\n\x0c\x64\x65\x63\x61y_factor\x18\x06 \x01(\x02\x12\r\n\x05\x63olor\x18\x07 \x01(\t\"F\n\x05\x45vent\x12\x11\n\x07picture\x18\x01 \x01(\x0cH\x00\x12\x0f\n\x05video\x18\x02 \x01(\x0cH\x00\x12\x0e\n\x04step\x18\x03 \x01(\tH\x00\x42\t\n\x07\x63ontentB Z\x1egithub.com/theo-m/physarium/pbb\x06proto3'
)



_CONFIG_INITDISTRIBUTION = _descriptor.EnumDescriptor(
  name='InitDistribution',
  full_name='physarium.Config.InitDistribution',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIFORM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CENTROIDS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CENTRE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRID', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=292,
  serialized_end=369,
)
_sym_db.RegisterEnumDescriptor(_CONFIG_INITDISTRIBUTION)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='physarium.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='physarium.Config.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='physarium.Config.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='particles', full_name='physarium.Config.particles', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iterations', full_name='physarium.Config.iterations', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blur_radius', full_name='physarium.Config.blur_radius', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blur_passes', full_name='physarium.Config.blur_passes', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoom_factor', full_name='physarium.Config.zoom_factor', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agents', full_name='physarium.Config.agents', index=7,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interaction_matrix', full_name='physarium.Config.interaction_matrix', index=8,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idist', full_name='physarium.Config.idist', index=9,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIG_INITDISTRIBUTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=369,
)


_AGENTCONFIG = _descriptor.Descriptor(
  name='AgentConfig',
  full_name='physarium.AgentConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_angle', full_name='physarium.AgentConfig.sensor_angle', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_distance', full_name='physarium.AgentConfig.sensor_distance', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation_angle', full_name='physarium.AgentConfig.rotation_angle', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step_distance', full_name='physarium.AgentConfig.step_distance', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deposition_amount', full_name='physarium.AgentConfig.deposition_amount', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decay_factor', full_name='physarium.AgentConfig.decay_factor', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='physarium.AgentConfig.color', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=543,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='physarium.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='picture', full_name='physarium.Event.picture', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video', full_name='physarium.Event.video', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='physarium.Event.step', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='physarium.Event.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=545,
  serialized_end=615,
)

_CONFIG.fields_by_name['agents'].message_type = _AGENTCONFIG
_CONFIG.fields_by_name['idist'].enum_type = _CONFIG_INITDISTRIBUTION
_CONFIG_INITDISTRIBUTION.containing_type = _CONFIG
_EVENT.oneofs_by_name['content'].fields.append(
  _EVENT.fields_by_name['picture'])
_EVENT.fields_by_name['picture'].containing_oneof = _EVENT.oneofs_by_name['content']
_EVENT.oneofs_by_name['content'].fields.append(
  _EVENT.fields_by_name['video'])
_EVENT.fields_by_name['video'].containing_oneof = _EVENT.oneofs_by_name['content']
_EVENT.oneofs_by_name['content'].fields.append(
  _EVENT.fields_by_name['step'])
_EVENT.fields_by_name['step'].containing_oneof = _EVENT.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['AgentConfig'] = _AGENTCONFIG
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'physarum_pb2'
  # @@protoc_insertion_point(class_scope:physarium.Config)
  })
_sym_db.RegisterMessage(Config)

AgentConfig = _reflection.GeneratedProtocolMessageType('AgentConfig', (_message.Message,), {
  'DESCRIPTOR' : _AGENTCONFIG,
  '__module__' : 'physarum_pb2'
  # @@protoc_insertion_point(class_scope:physarium.AgentConfig)
  })
_sym_db.RegisterMessage(AgentConfig)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'physarum_pb2'
  # @@protoc_insertion_point(class_scope:physarium.Event)
  })
_sym_db.RegisterMessage(Event)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
