# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Config(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    InitDistributionValue = typing___NewType('InitDistributionValue', builtin___int)
    type___InitDistributionValue = InitDistributionValue
    InitDistribution: _InitDistribution
    class _InitDistribution(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[Config.InitDistributionValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNK = typing___cast(Config.InitDistributionValue, 0)
        UNIFORM = typing___cast(Config.InitDistributionValue, 1)
        CENTROIDS = typing___cast(Config.InitDistributionValue, 2)
        CENTRE = typing___cast(Config.InitDistributionValue, 3)
        GRID = typing___cast(Config.InitDistributionValue, 4)
    UNK = typing___cast(Config.InitDistributionValue, 0)
    UNIFORM = typing___cast(Config.InitDistributionValue, 1)
    CENTROIDS = typing___cast(Config.InitDistributionValue, 2)
    CENTRE = typing___cast(Config.InitDistributionValue, 3)
    GRID = typing___cast(Config.InitDistributionValue, 4)
    type___InitDistribution = InitDistribution

    width: builtin___int = ...
    height: builtin___int = ...
    particles: builtin___int = ...
    iterations: builtin___int = ...
    blur_radius: builtin___int = ...
    blur_passes: builtin___int = ...
    zoom_factor: builtin___float = ...
    gamma: builtin___float = ...
    interaction_matrix: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...
    idist: type___Config.InitDistributionValue = ...
    gaussian_sigma: builtin___float = ...
    box: builtin___float = ...

    @property
    def agents(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___AgentConfig]: ...

    def __init__(self,
        *,
        width : typing___Optional[builtin___int] = None,
        height : typing___Optional[builtin___int] = None,
        particles : typing___Optional[builtin___int] = None,
        iterations : typing___Optional[builtin___int] = None,
        blur_radius : typing___Optional[builtin___int] = None,
        blur_passes : typing___Optional[builtin___int] = None,
        zoom_factor : typing___Optional[builtin___float] = None,
        gamma : typing___Optional[builtin___float] = None,
        agents : typing___Optional[typing___Iterable[type___AgentConfig]] = None,
        interaction_matrix : typing___Optional[typing___Iterable[builtin___float]] = None,
        idist : typing___Optional[type___Config.InitDistributionValue] = None,
        gaussian_sigma : typing___Optional[builtin___float] = None,
        box : typing___Optional[builtin___float] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"box",b"box",u"decay_type",b"decay_type",u"gaussian_sigma",b"gaussian_sigma"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"agents",b"agents",u"blur_passes",b"blur_passes",u"blur_radius",b"blur_radius",u"box",b"box",u"decay_type",b"decay_type",u"gamma",b"gamma",u"gaussian_sigma",b"gaussian_sigma",u"height",b"height",u"idist",b"idist",u"interaction_matrix",b"interaction_matrix",u"iterations",b"iterations",u"particles",b"particles",u"width",b"width",u"zoom_factor",b"zoom_factor"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"decay_type",b"decay_type"]) -> typing_extensions___Literal["gaussian_sigma","box"]: ...
type___Config = Config

class AgentConfig(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    sensor_angle: builtin___float = ...
    sensor_distance: builtin___float = ...
    rotation_angle: builtin___float = ...
    step_distance: builtin___float = ...
    deposition_amount: builtin___float = ...
    decay_factor: builtin___float = ...
    color: typing___Text = ...

    def __init__(self,
        *,
        sensor_angle : typing___Optional[builtin___float] = None,
        sensor_distance : typing___Optional[builtin___float] = None,
        rotation_angle : typing___Optional[builtin___float] = None,
        step_distance : typing___Optional[builtin___float] = None,
        deposition_amount : typing___Optional[builtin___float] = None,
        decay_factor : typing___Optional[builtin___float] = None,
        color : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"color",b"color",u"decay_factor",b"decay_factor",u"deposition_amount",b"deposition_amount",u"rotation_angle",b"rotation_angle",u"sensor_angle",b"sensor_angle",u"sensor_distance",b"sensor_distance",u"step_distance",b"step_distance"]) -> None: ...
type___AgentConfig = AgentConfig

class Event(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    picture: builtin___bytes = ...
    video: builtin___bytes = ...
    step: typing___Text = ...
    model_id: typing___Text = ...

    def __init__(self,
        *,
        picture : typing___Optional[builtin___bytes] = None,
        video : typing___Optional[builtin___bytes] = None,
        step : typing___Optional[typing___Text] = None,
        model_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"content",b"content",u"model_id",b"model_id",u"picture",b"picture",u"step",b"step",u"video",b"video"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content",b"content",u"model_id",b"model_id",u"picture",b"picture",u"step",b"step",u"video",b"video"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"content",b"content"]) -> typing_extensions___Literal["picture","video","step","model_id"]: ...
type___Event = Event
